name: SLSA go releaser
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{github.sha}}
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # tag=v5.0.2
        with:
          go-version: '1.23.1'
      - name: Verify using gitverify
        run: |
          go install github.com/supply-chain-tools/go-sandbox/cmd/gitverify@v0.0.0-20241001120425-508aea1fc47d
          wget https://raw.githubusercontent.com/supply-chain-tools/root-of-trust/refs/heads/main/gitverify.json
          if [ "$(sha256sum gitverify.json | cut -d ' ' -f1)" != "8b5f21fe1a8f49a1b795ca57de600a4465c7e566ca3895ddf9bf7d7899c31ac4" ]; then exit 1; fi
          git checkout main
          git checkout ${{github.sha}}
          ~/go/bin/gitverify --config-file gitverify.json --repository-uri git+https://github.com/supply-chain-tools/release-prototype.git --commit ${{github.sha}} --branch main --tag ${{github.ref_name}}
  args:
    runs-on: ubuntu-latest
    needs: verify
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
    steps:
      - id: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version-file: go.mod
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"
